"""empty message

Revision ID: 17325a6c5f26
Revises: 4f52e3f0b4c5
Create Date: 2014-11-16 01:01:40.961000

"""

# revision identifiers, used by Alembic.
revision = '17325a6c5f26'
down_revision = '4f52e3f0b4c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('repo_id', sa.String(length=200), nullable=True),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('log_path', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    ### end Alembic commands ###
