"""empty message

Revision ID: 2e70ece0ab5d
Revises: 59739cd77011
Create Date: 2014-11-16 11:52:54.671000

"""

# revision identifiers, used by Alembic.
revision = '2e70ece0ab5d'
down_revision = '59739cd77011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_status', sa.Column('status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_status', 'status')
    ### end Alembic commands ###
