"""empty message

Revision ID: 463d0aac1bc
Revises: 2e70ece0ab5d
Create Date: 2014-11-16 21:38:01.288000

"""

# revision identifiers, used by Alembic.
revision = '463d0aac1bc'
down_revision = '2e70ece0ab5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_status', sa.Column('desc', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_status', 'desc')
    ### end Alembic commands ###
