"""empty message

Revision ID: 59739cd77011
Revises: 17325a6c5f26
Create Date: 2014-11-16 11:12:11.994000

"""

# revision identifiers, used by Alembic.
revision = '59739cd77011'
down_revision = '17325a6c5f26'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_status', sa.Column('percent', sa.Integer(), nullable=True))
    op.add_column('upload_status', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('upload_status', sa.Column('repo_id', sa.String(length=200), nullable=True))
    op.drop_column('upload_status', 'success')
    op.drop_column('upload_status', 'file_name')
    op.drop_column('upload_status', 'current')
    op.drop_column('upload_status', 'file_id')
    op.drop_column('upload_status', 'status_code')
    op.drop_column('upload_status', 'total')
    op.drop_column('upload_status', 'speed')
    op.drop_column('upload_status', 'spend')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_status', sa.Column('spend', mysql.DATETIME(), nullable=True))
    op.add_column('upload_status', sa.Column('speed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('upload_status', sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('upload_status', sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('upload_status', sa.Column('file_id', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('upload_status', sa.Column('current', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('upload_status', sa.Column('file_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('upload_status', sa.Column('success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('upload_status', 'repo_id')
    op.drop_column('upload_status', 'rate')
    op.drop_column('upload_status', 'percent')
    ### end Alembic commands ###
